[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DRETROGO_TARGET_ESP32
  -DCORE_DEBUG_LEVEL=0
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.43
  earlephilhower/ESP8266 and ESP32 Oled Driver for SSD1306 display @ ^4.0.0
